export const rolePermissions = {
  faculty: new Set([
    "/",
    "/students",
    "/students/profiles",
    "/academics/courses",
    "/batches",
    "/faculty",
    "/attendance",
    "/tests",
    "/academics/question-bank",
    "/academics/results",
    "/academics/assignments",
    "/academics/study-materials",
    "/academics/doubts",
    "/analytics/student-performance",
    "/analytics/attendance",
    "/ai-assistant",
    "/settings/system",
  ]),
  counsellor: new Set([
    "/",
    "/students",
    "/students/profiles",
    "/leads",
    "/admissions/counselling",
    "/admissions",
    "/analytics/lead-conversion",
    "/communication/notifications",
    "/communication/whatsapp",
    "/communication/sms-email",
    "/communication/announcements",
    "/ai-assistant",
    "/settings/system",
  ]),
  student: new Set([
    "/",
    "/students/profiles",
    "/academics/courses",
    "/batches",
    "/attendance",
    "/tests",
    "/academics/results",
    "/academics/assignments",
    "/academics/study-materials",
    "/academics/doubts",
    "/fees",
    "/ai-assistant",
    "/settings/system",
  ]),
};

export const validRoles = ["admin", "faculty", "counsellor", "student"];
